###
GET http://localhost:7070/api/msg/hello

###
POST http://localhost:7070/api/auth/register

{
"username": "user1",
"password": "pass123"
}

###
POST http://localhost:7070/api/auth/login

{
"username": "user1",
"password": "pass123"
}

###
GET http://localhost:7070/api/auth/userprotected
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIlRob21hcyBIYXJ0bWFublwiIiwic3ViIjoiZnJvbVJlc3QzIiwiZXhwIjoxNzc4MDk3NjgxLCJyb2xlcyI6InVzZXIiLCJ1c2VybmFtZSI6ImZyb21SZXN0MyJ9.8d4zD9lFgSmgRGVHJ3-LtSl_HVXijH1Ji9_WkO-h7LY