###
GET http://localhost:7070/api/msg/hello

###
POST http://localhost:7070/api/auth/register

{
"username": "user1",
"password": "pass123"
}

###
POST http://localhost:7070/api/auth/login

{
"username": "user1",
"password": "pass123"
}

###
GET http://localhost:7070/api/auth/userprotected
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIlRob21hcyBIYXJ0bWFublwiIiwic3ViIjoidXNlcjEiLCJleHAiOjE3NzgyMzc4MTksInJvbGVzIjoidXNlciIsInVzZXJuYW1lIjoidXNlcjEifQ.2-silx9SnJ_BMl5QRfyJ8woHmO5bwhnYH4RdxEYqzSQ